# Generated by Django 5.2 on 2025-04-18 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configapp', '0004_room_tabletype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupstudent',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_courses', to='configapp.course'),
        ),
        migrations.AlterField(
            model_name='groupstudent',
            name='table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='configapp.table'),
        ),
        migrations.AlterField(
            model_name='groupstudent',
            name='teacher',
            field=models.ManyToManyField(blank=True, null=True, related_name='teacher_get', to='configapp.teacher'),
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='course',
        ),
        migrations.AlterField(
            model_name='teacher',
            name='departments',
            field=models.ManyToManyField(blank=True, null=True, related_name='get_department', to='configapp.departments'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_courses', to='configapp.course'),
        ),
    ]
